# Generated by Django 3.0 on 2020-05-20 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 12, 22, 33, 570152, tzinfo=utc)),
        ),
    ]
