# Generated by Django 3.0 on 2020-05-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20200520_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
