# Generated by Django 3.0 on 2020-07-14 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0009_auto_20200704_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='list',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
